# Generated by Django 5.2.17 on 2026-10-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoSeedState",
            fields=[
                (
                    "key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
